### ISSUE TITLE
Calculate the multiplication and sum of two numbers in python

### ISSUE THREAD

**Issue by Gaurika-Gupta** [ayushh-gautam/HakcotberFest2022#1]

**Comment by Gaurika-Gupta** [comment]
Please assign me this issue under Hacktoberfest 2022 after adding the necessary Labels

**Comment by ayushh-gautam** [comment]
sorry to say but i cant be alble to assign this issue because i am not a maintainer even if i did assign it wont count

**Comment by ayushh-gautam** [comment]
how to assign i am new to github so i dont know much

**Comment by Gaurika-Gupta** [comment]
On this page, Besides the comments you can see Assignees, probably click on that and then you might be able to add me then I will be assigned the issue.

**Comment by ayushh-gautam** [comment]
your name is not shown in the Asignees, why is that so?
could you tell me more how to add i would love to assign this to you asap

**Comment by ayushh-gautam** [comment]
alright i assigned you now your name was not shown in the assign list before now it is shown well
